name:                WSMoolticute
version:             0.1.0.0
github:              "githubuser/WSMoolticute"
license:             BSD3
author:              "Grandison Research Group"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/githubuser/WSMoolticute#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- mtl
- websockets
- random

library:
  source-dirs: src

executables:
  WSMoolticute-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - WSMoolticute

tests:
  WSMoolticute-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - WSMoolticute
